
version: '3'

services:
  producer:
    image: housepricepred-producer
    #deploy:
      #replicas: 1
    build: Kafka-Producer
    environment:
       BROKER: kafka:9092
       command: "python Kafka-Producer/src/TestDataStreamProducer.py"
    ports:
      - "8888:8888"

  consumer:
    image: housepricepred-consumer
    #deploy:
      #replicas: 1
    build: Kafka-Consumer
    environment:
       BROKER: kafka:9092  
    depends_on:
       - producer
    ports:
      - "7777:7777"
